spring:
  data:
    mongodb:
      uri: ${DISCORD_API_MONGO_URI}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AS_JWT_ISSUER_URI}
  profiles:
    active: "prod"
  rabbitmq:
    host: ${RABBITMQ_HOST}
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
server:
  error:
    whitelabel:
      enabled: false