logging:
  level:
    org:
      springframework:
        security: INFO
    DiscordFetcher: INFO
spring:
  devtools:
    remote:
      secret: ${DEVTOOLS_REMOTE_SECRET}
    restart:
      enabled: true