spring:
  data:
    mongodb:
      uri: ${DISCORD_API_MONGO_URI}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AS_JWT_ISSUER_URI}
  profiles:
    active: "prod"
server:
  error:
    whitelabel:
      enabled: false